-- Let It Cast — reference data (not demo data).
--
-- Languages and the canonical skill list are part of the product, not of the
-- seed: they power autocomplete on both the talent profile and role criteria.

insert into public.languages (code, name) values
  ('en', 'English'),
  ('fr', 'French'),
  ('es', 'Spanish'),
  ('it', 'Italian'),
  ('de', 'German'),
  ('pt', 'Portuguese'),
  ('ar', 'Arabic'),
  ('he', 'Hebrew'),
  ('ru', 'Russian'),
  ('uk', 'Ukrainian'),
  ('pl', 'Polish'),
  ('zh', 'Mandarin'),
  ('yue', 'Cantonese'),
  ('ja', 'Japanese'),
  ('ko', 'Korean'),
  ('hi', 'Hindi'),
  ('ur', 'Urdu'),
  ('tr', 'Turkish'),
  ('fa', 'Farsi'),
  ('nl', 'Dutch'),
  ('sv', 'Swedish'),
  ('da', 'Danish'),
  ('no', 'Norwegian'),
  ('fi', 'Finnish'),
  ('el', 'Greek'),
  ('ro', 'Romanian'),
  ('hu', 'Hungarian'),
  ('cs', 'Czech'),
  ('yo', 'Yoruba'),
  ('sw', 'Swahili'),
  ('vi', 'Vietnamese'),
  ('th', 'Thai'),
  ('id', 'Indonesian'),
  ('tl', 'Tagalog'),
  ('bn', 'Bengali'),
  ('ta', 'Tamil'),
  ('yi', 'Yiddish'),
  ('ca', 'Catalan'),
  ('eu', 'Basque'),
  ('ga', 'Irish')
on conflict (code) do nothing;

insert into public.skills (name, category) values
  -- Performance
  ('Drama', 'performance'),
  ('Comedy', 'performance'),
  ('Improvisation', 'performance'),
  ('Vulnerability', 'performance'),
  ('Comedic timing', 'performance'),
  ('Physical theatre', 'performance'),
  ('Voice acting', 'performance'),
  ('Motion capture', 'performance'),
  ('Classical / Shakespeare', 'performance'),
  ('Musical theatre', 'performance'),
  ('Stand-up', 'performance'),
  ('Presenting', 'performance'),
  -- Music
  ('Singing', 'music'),
  ('Opera', 'music'),
  ('Guitar', 'music'),
  ('Piano', 'music'),
  ('Violin', 'music'),
  ('Drums', 'music'),
  ('Saxophone', 'music'),
  -- Dance
  ('Contemporary dance', 'dance'),
  ('Ballet', 'dance'),
  ('Hip-hop', 'dance'),
  ('Tap', 'dance'),
  ('Ballroom', 'dance'),
  -- Sport & stunts
  ('Stage combat', 'stunts'),
  ('Martial arts', 'stunts'),
  ('Boxing', 'sport'),
  ('Fencing', 'sport'),
  ('Swimming', 'sport'),
  ('Horse riding', 'sport'),
  ('Skateboarding', 'sport'),
  ('Skiing', 'sport'),
  ('Climbing', 'sport'),
  ('Gymnastics', 'sport'),
  ('Yoga', 'sport'),
  -- Licences & practical
  ('Driving licence', 'practical'),
  ('Motorcycle licence', 'practical'),
  ('Heavy vehicle licence', 'practical'),
  ('Sign language', 'practical'),
  ('Cooking', 'practical'),
  ('Puppetry', 'practical')
on conflict (name) do nothing;
